choco install paint.net -y
choco install javaruntime -y
choco install mp3tag -y
choco install mpc-hc -y
choco install musescore -y
choco install nodejs -y
choco install postman -y
choco install tagspaces -y
choco install vlc -y
choco install vnc-viewer -y
